// Code generated by mockery. DO NOT EDIT.

package usecasemocks

import (
	context "context"

	domain "github.com/paxaf/itkFinal/gw-notification/internal/domain"
	usecase "github.com/paxaf/itkFinal/gw-notification/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// LargeOperationHandlerMock is an autogenerated mock type for the LargeOperationHandler type
type LargeOperationHandlerMock struct {
	mock.Mock
}

type LargeOperationHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LargeOperationHandlerMock) EXPECT() *LargeOperationHandlerMock_Expecter {
	return &LargeOperationHandlerMock_Expecter{mock: &_m.Mock}
}

// HandleLargeOperation provides a mock function with given fields: ctx, event
func (_m *LargeOperationHandlerMock) HandleLargeOperation(ctx context.Context, event domain.LargeOperationEvent) (usecase.HandleLargeOperationsResult, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleLargeOperation")
	}

	var r0 usecase.HandleLargeOperationsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LargeOperationEvent) (usecase.HandleLargeOperationsResult, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.LargeOperationEvent) usecase.HandleLargeOperationsResult); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(usecase.HandleLargeOperationsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.LargeOperationEvent) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LargeOperationHandlerMock_HandleLargeOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleLargeOperation'
type LargeOperationHandlerMock_HandleLargeOperation_Call struct {
	*mock.Call
}

// HandleLargeOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.LargeOperationEvent
func (_e *LargeOperationHandlerMock_Expecter) HandleLargeOperation(ctx interface{}, event interface{}) *LargeOperationHandlerMock_HandleLargeOperation_Call {
	return &LargeOperationHandlerMock_HandleLargeOperation_Call{Call: _e.mock.On("HandleLargeOperation", ctx, event)}
}

func (_c *LargeOperationHandlerMock_HandleLargeOperation_Call) Run(run func(ctx context.Context, event domain.LargeOperationEvent)) *LargeOperationHandlerMock_HandleLargeOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.LargeOperationEvent))
	})
	return _c
}

func (_c *LargeOperationHandlerMock_HandleLargeOperation_Call) Return(_a0 usecase.HandleLargeOperationsResult, _a1 error) *LargeOperationHandlerMock_HandleLargeOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LargeOperationHandlerMock_HandleLargeOperation_Call) RunAndReturn(run func(context.Context, domain.LargeOperationEvent) (usecase.HandleLargeOperationsResult, error)) *LargeOperationHandlerMock_HandleLargeOperation_Call {
	_c.Call.Return(run)
	return _c
}

// HandleLargeOperations provides a mock function with given fields: ctx, events
func (_m *LargeOperationHandlerMock) HandleLargeOperations(ctx context.Context, events []domain.LargeOperationEvent) (usecase.HandleLargeOperationsResult, error) {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for HandleLargeOperations")
	}

	var r0 usecase.HandleLargeOperationsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.LargeOperationEvent) (usecase.HandleLargeOperationsResult, error)); ok {
		return rf(ctx, events)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []domain.LargeOperationEvent) usecase.HandleLargeOperationsResult); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Get(0).(usecase.HandleLargeOperationsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []domain.LargeOperationEvent) error); ok {
		r1 = rf(ctx, events)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LargeOperationHandlerMock_HandleLargeOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleLargeOperations'
type LargeOperationHandlerMock_HandleLargeOperations_Call struct {
	*mock.Call
}

// HandleLargeOperations is a helper method to define mock.On call
//   - ctx context.Context
//   - events []domain.LargeOperationEvent
func (_e *LargeOperationHandlerMock_Expecter) HandleLargeOperations(ctx interface{}, events interface{}) *LargeOperationHandlerMock_HandleLargeOperations_Call {
	return &LargeOperationHandlerMock_HandleLargeOperations_Call{Call: _e.mock.On("HandleLargeOperations", ctx, events)}
}

func (_c *LargeOperationHandlerMock_HandleLargeOperations_Call) Run(run func(ctx context.Context, events []domain.LargeOperationEvent)) *LargeOperationHandlerMock_HandleLargeOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.LargeOperationEvent))
	})
	return _c
}

func (_c *LargeOperationHandlerMock_HandleLargeOperations_Call) Return(_a0 usecase.HandleLargeOperationsResult, _a1 error) *LargeOperationHandlerMock_HandleLargeOperations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LargeOperationHandlerMock_HandleLargeOperations_Call) RunAndReturn(run func(context.Context, []domain.LargeOperationEvent) (usecase.HandleLargeOperationsResult, error)) *LargeOperationHandlerMock_HandleLargeOperations_Call {
	_c.Call.Return(run)
	return _c
}

// NewLargeOperationHandlerMock creates a new instance of LargeOperationHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLargeOperationHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LargeOperationHandlerMock {
	mock := &LargeOperationHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
