// Code generated by mockery. DO NOT EDIT.

package storagesmocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// StorageMock is an autogenerated mock type for the Storage type
type StorageMock struct {
	mock.Mock
}

type StorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageMock) EXPECT() *StorageMock_Expecter {
	return &StorageMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *StorageMock) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type StorageMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *StorageMock_Expecter) Close() *StorageMock_Close_Call {
	return &StorageMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *StorageMock_Close_Call) Run(run func()) *StorageMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StorageMock_Close_Call) Return(_a0 error) *StorageMock_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_Close_Call) RunAndReturn(run func() error) *StorageMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetRate provides a mock function with given fields: ctx, from, to
func (_m *StorageMock) GetRate(ctx context.Context, from string, to string) (float64, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetRate")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (float64, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) float64); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_GetRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRate'
type StorageMock_GetRate_Call struct {
	*mock.Call
}

// GetRate is a helper method to define mock.On call
//   - ctx context.Context
//   - from string
//   - to string
func (_e *StorageMock_Expecter) GetRate(ctx interface{}, from interface{}, to interface{}) *StorageMock_GetRate_Call {
	return &StorageMock_GetRate_Call{Call: _e.mock.On("GetRate", ctx, from, to)}
}

func (_c *StorageMock_GetRate_Call) Run(run func(ctx context.Context, from string, to string)) *StorageMock_GetRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *StorageMock_GetRate_Call) Return(_a0 float64, _a1 error) *StorageMock_GetRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_GetRate_Call) RunAndReturn(run func(context.Context, string, string) (float64, error)) *StorageMock_GetRate_Call {
	_c.Call.Return(run)
	return _c
}

// GetRates provides a mock function with given fields: ctx
func (_m *StorageMock) GetRates(ctx context.Context) (map[string]float64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRates")
	}

	var r0 map[string]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]float64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]float64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_GetRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRates'
type StorageMock_GetRates_Call struct {
	*mock.Call
}

// GetRates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StorageMock_Expecter) GetRates(ctx interface{}) *StorageMock_GetRates_Call {
	return &StorageMock_GetRates_Call{Call: _e.mock.On("GetRates", ctx)}
}

func (_c *StorageMock_GetRates_Call) Run(run func(ctx context.Context)) *StorageMock_GetRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StorageMock_GetRates_Call) Return(_a0 map[string]float64, _a1 error) *StorageMock_GetRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_GetRates_Call) RunAndReturn(run func(context.Context) (map[string]float64, error)) *StorageMock_GetRates_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageMock creates a new instance of StorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageMock {
	mock := &StorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
