// Code generated by mockery. DO NOT EDIT.

package usecasemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExchangerMock is an autogenerated mock type for the Exchanger type
type ExchangerMock struct {
	mock.Mock
}

type ExchangerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ExchangerMock) EXPECT() *ExchangerMock_Expecter {
	return &ExchangerMock_Expecter{mock: &_m.Mock}
}

// GetRate provides a mock function with given fields: ctx, from, to
func (_m *ExchangerMock) GetRate(ctx context.Context, from string, to string) (float64, error) {
	ret := _m.Called(ctx, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetRate")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (float64, error)); ok {
		return rf(ctx, from, to)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) float64); ok {
		r0 = rf(ctx, from, to)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, from, to)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExchangerMock_GetRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRate'
type ExchangerMock_GetRate_Call struct {
	*mock.Call
}

// GetRate is a helper method to define mock.On call
//   - ctx context.Context
//   - from string
//   - to string
func (_e *ExchangerMock_Expecter) GetRate(ctx interface{}, from interface{}, to interface{}) *ExchangerMock_GetRate_Call {
	return &ExchangerMock_GetRate_Call{Call: _e.mock.On("GetRate", ctx, from, to)}
}

func (_c *ExchangerMock_GetRate_Call) Run(run func(ctx context.Context, from string, to string)) *ExchangerMock_GetRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ExchangerMock_GetRate_Call) Return(_a0 float64, _a1 error) *ExchangerMock_GetRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExchangerMock_GetRate_Call) RunAndReturn(run func(context.Context, string, string) (float64, error)) *ExchangerMock_GetRate_Call {
	_c.Call.Return(run)
	return _c
}

// GetRates provides a mock function with given fields: ctx
func (_m *ExchangerMock) GetRates(ctx context.Context) (map[string]float64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRates")
	}

	var r0 map[string]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]float64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]float64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExchangerMock_GetRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRates'
type ExchangerMock_GetRates_Call struct {
	*mock.Call
}

// GetRates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ExchangerMock_Expecter) GetRates(ctx interface{}) *ExchangerMock_GetRates_Call {
	return &ExchangerMock_GetRates_Call{Call: _e.mock.On("GetRates", ctx)}
}

func (_c *ExchangerMock_GetRates_Call) Run(run func(ctx context.Context)) *ExchangerMock_GetRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ExchangerMock_GetRates_Call) Return(_a0 map[string]float64, _a1 error) *ExchangerMock_GetRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExchangerMock_GetRates_Call) RunAndReturn(run func(context.Context) (map[string]float64, error)) *ExchangerMock_GetRates_Call {
	_c.Call.Return(run)
	return _c
}

// NewExchangerMock creates a new instance of ExchangerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExchangerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExchangerMock {
	mock := &ExchangerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
