// Code generated by mockery. DO NOT EDIT.

package usecasemocks

import (
	context "context"

	domain "github.com/paxaf/itkFinal/gw-analytics/internal/domain"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/paxaf/itkFinal/gw-analytics/internal/usecase"
)

// OperationHandlerMock is an autogenerated mock type for the OperationHandler type
type OperationHandlerMock struct {
	mock.Mock
}

type OperationHandlerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *OperationHandlerMock) EXPECT() *OperationHandlerMock_Expecter {
	return &OperationHandlerMock_Expecter{mock: &_m.Mock}
}

// HandleOperation provides a mock function with given fields: ctx, event
func (_m *OperationHandlerMock) HandleOperation(ctx context.Context, event domain.OperationEvent) (usecase.HandleOperationsResult, error) {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for HandleOperation")
	}

	var r0 usecase.HandleOperationsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.OperationEvent) (usecase.HandleOperationsResult, error)); ok {
		return rf(ctx, event)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.OperationEvent) usecase.HandleOperationsResult); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Get(0).(usecase.HandleOperationsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.OperationEvent) error); ok {
		r1 = rf(ctx, event)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OperationHandlerMock_HandleOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleOperation'
type OperationHandlerMock_HandleOperation_Call struct {
	*mock.Call
}

// HandleOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.OperationEvent
func (_e *OperationHandlerMock_Expecter) HandleOperation(ctx interface{}, event interface{}) *OperationHandlerMock_HandleOperation_Call {
	return &OperationHandlerMock_HandleOperation_Call{Call: _e.mock.On("HandleOperation", ctx, event)}
}

func (_c *OperationHandlerMock_HandleOperation_Call) Run(run func(ctx context.Context, event domain.OperationEvent)) *OperationHandlerMock_HandleOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.OperationEvent))
	})
	return _c
}

func (_c *OperationHandlerMock_HandleOperation_Call) Return(_a0 usecase.HandleOperationsResult, _a1 error) *OperationHandlerMock_HandleOperation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OperationHandlerMock_HandleOperation_Call) RunAndReturn(run func(context.Context, domain.OperationEvent) (usecase.HandleOperationsResult, error)) *OperationHandlerMock_HandleOperation_Call {
	_c.Call.Return(run)
	return _c
}

// HandleOperations provides a mock function with given fields: ctx, events
func (_m *OperationHandlerMock) HandleOperations(ctx context.Context, events []domain.OperationEvent) (usecase.HandleOperationsResult, error) {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for HandleOperations")
	}

	var r0 usecase.HandleOperationsResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.OperationEvent) (usecase.HandleOperationsResult, error)); ok {
		return rf(ctx, events)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []domain.OperationEvent) usecase.HandleOperationsResult); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Get(0).(usecase.HandleOperationsResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, []domain.OperationEvent) error); ok {
		r1 = rf(ctx, events)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// OperationHandlerMock_HandleOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleOperations'
type OperationHandlerMock_HandleOperations_Call struct {
	*mock.Call
}

// HandleOperations is a helper method to define mock.On call
//   - ctx context.Context
//   - events []domain.OperationEvent
func (_e *OperationHandlerMock_Expecter) HandleOperations(ctx interface{}, events interface{}) *OperationHandlerMock_HandleOperations_Call {
	return &OperationHandlerMock_HandleOperations_Call{Call: _e.mock.On("HandleOperations", ctx, events)}
}

func (_c *OperationHandlerMock_HandleOperations_Call) Run(run func(ctx context.Context, events []domain.OperationEvent)) *OperationHandlerMock_HandleOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.OperationEvent))
	})
	return _c
}

func (_c *OperationHandlerMock_HandleOperations_Call) Return(_a0 usecase.HandleOperationsResult, _a1 error) *OperationHandlerMock_HandleOperations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *OperationHandlerMock_HandleOperations_Call) RunAndReturn(run func(context.Context, []domain.OperationEvent) (usecase.HandleOperationsResult, error)) *OperationHandlerMock_HandleOperations_Call {
	_c.Call.Return(run)
	return _c
}

// NewOperationHandlerMock creates a new instance of OperationHandlerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOperationHandlerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *OperationHandlerMock {
	mock := &OperationHandlerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
