// Code generated by mockery. DO NOT EDIT.

package storagesmocks

import (
	context "context"

	domain "github.com/paxaf/itkFinal/gw-currency-wallet/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// StorageMock is an autogenerated mock type for the Storage type
type StorageMock struct {
	mock.Mock
}

type StorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageMock) EXPECT() *StorageMock_Expecter {
	return &StorageMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *StorageMock) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type StorageMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *StorageMock_Expecter) Close() *StorageMock_Close_Call {
	return &StorageMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *StorageMock_Close_Call) Run(run func()) *StorageMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StorageMock_Close_Call) Return(_a0 error) *StorageMock_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_Close_Call) RunAndReturn(run func() error) *StorageMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUser provides a mock function with given fields: ctx, username, email, passwordHash
func (_m *StorageMock) CreateUser(ctx context.Context, username string, email string, passwordHash string) (domain.User, error) {
	ret := _m.Called(ctx, username, email, passwordHash)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (domain.User, error)); ok {
		return rf(ctx, username, email, passwordHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) domain.User); ok {
		r0 = rf(ctx, username, email, passwordHash)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, username, email, passwordHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_CreateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUser'
type StorageMock_CreateUser_Call struct {
	*mock.Call
}

// CreateUser is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
//   - email string
//   - passwordHash string
func (_e *StorageMock_Expecter) CreateUser(ctx interface{}, username interface{}, email interface{}, passwordHash interface{}) *StorageMock_CreateUser_Call {
	return &StorageMock_CreateUser_Call{Call: _e.mock.On("CreateUser", ctx, username, email, passwordHash)}
}

func (_c *StorageMock_CreateUser_Call) Run(run func(ctx context.Context, username string, email string, passwordHash string)) *StorageMock_CreateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *StorageMock_CreateUser_Call) Return(_a0 domain.User, _a1 error) *StorageMock_CreateUser_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_CreateUser_Call) RunAndReturn(run func(context.Context, string, string, string) (domain.User, error)) *StorageMock_CreateUser_Call {
	_c.Call.Return(run)
	return _c
}

// Deposit provides a mock function with given fields: ctx, userID, currency, amountMinor
func (_m *StorageMock) Deposit(ctx context.Context, userID int64, currency domain.Currency, amountMinor int64) (map[string]int64, error) {
	ret := _m.Called(ctx, userID, currency, amountMinor)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Currency, int64) (map[string]int64, error)); ok {
		return rf(ctx, userID, currency, amountMinor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Currency, int64) map[string]int64); ok {
		r0 = rf(ctx, userID, currency, amountMinor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.Currency, int64) error); ok {
		r1 = rf(ctx, userID, currency, amountMinor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type StorageMock_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - currency domain.Currency
//   - amountMinor int64
func (_e *StorageMock_Expecter) Deposit(ctx interface{}, userID interface{}, currency interface{}, amountMinor interface{}) *StorageMock_Deposit_Call {
	return &StorageMock_Deposit_Call{Call: _e.mock.On("Deposit", ctx, userID, currency, amountMinor)}
}

func (_c *StorageMock_Deposit_Call) Run(run func(ctx context.Context, userID int64, currency domain.Currency, amountMinor int64)) *StorageMock_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.Currency), args[3].(int64))
	})
	return _c
}

func (_c *StorageMock_Deposit_Call) Return(_a0 map[string]int64, _a1 error) *StorageMock_Deposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_Deposit_Call) RunAndReturn(run func(context.Context, int64, domain.Currency, int64) (map[string]int64, error)) *StorageMock_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function with given fields: ctx, userID, fromCurrency, toCurrency, fromAmountMinor, toAmountMinor
func (_m *StorageMock) Exchange(ctx context.Context, userID int64, fromCurrency domain.Currency, toCurrency domain.Currency, fromAmountMinor int64, toAmountMinor int64) (map[string]int64, error) {
	ret := _m.Called(ctx, userID, fromCurrency, toCurrency, fromAmountMinor, toAmountMinor)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Currency, domain.Currency, int64, int64) (map[string]int64, error)); ok {
		return rf(ctx, userID, fromCurrency, toCurrency, fromAmountMinor, toAmountMinor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Currency, domain.Currency, int64, int64) map[string]int64); ok {
		r0 = rf(ctx, userID, fromCurrency, toCurrency, fromAmountMinor, toAmountMinor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.Currency, domain.Currency, int64, int64) error); ok {
		r1 = rf(ctx, userID, fromCurrency, toCurrency, fromAmountMinor, toAmountMinor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type StorageMock_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - fromCurrency domain.Currency
//   - toCurrency domain.Currency
//   - fromAmountMinor int64
//   - toAmountMinor int64
func (_e *StorageMock_Expecter) Exchange(ctx interface{}, userID interface{}, fromCurrency interface{}, toCurrency interface{}, fromAmountMinor interface{}, toAmountMinor interface{}) *StorageMock_Exchange_Call {
	return &StorageMock_Exchange_Call{Call: _e.mock.On("Exchange", ctx, userID, fromCurrency, toCurrency, fromAmountMinor, toAmountMinor)}
}

func (_c *StorageMock_Exchange_Call) Run(run func(ctx context.Context, userID int64, fromCurrency domain.Currency, toCurrency domain.Currency, fromAmountMinor int64, toAmountMinor int64)) *StorageMock_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.Currency), args[3].(domain.Currency), args[4].(int64), args[5].(int64))
	})
	return _c
}

func (_c *StorageMock_Exchange_Call) Return(_a0 map[string]int64, _a1 error) *StorageMock_Exchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_Exchange_Call) RunAndReturn(run func(context.Context, int64, domain.Currency, domain.Currency, int64, int64) (map[string]int64, error)) *StorageMock_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalances provides a mock function with given fields: ctx, userID
func (_m *StorageMock) GetBalances(ctx context.Context, userID int64) (map[string]int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalances")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (map[string]int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) map[string]int64); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_GetBalances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalances'
type StorageMock_GetBalances_Call struct {
	*mock.Call
}

// GetBalances is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *StorageMock_Expecter) GetBalances(ctx interface{}, userID interface{}) *StorageMock_GetBalances_Call {
	return &StorageMock_GetBalances_Call{Call: _e.mock.On("GetBalances", ctx, userID)}
}

func (_c *StorageMock_GetBalances_Call) Run(run func(ctx context.Context, userID int64)) *StorageMock_GetBalances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *StorageMock_GetBalances_Call) Return(_a0 map[string]int64, _a1 error) *StorageMock_GetBalances_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_GetBalances_Call) RunAndReturn(run func(context.Context, int64) (map[string]int64, error)) *StorageMock_GetBalances_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserCredentialsByUsername provides a mock function with given fields: ctx, username
func (_m *StorageMock) GetUserCredentialsByUsername(ctx context.Context, username string) (domain.UserCredentials, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserCredentialsByUsername")
	}

	var r0 domain.UserCredentials
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.UserCredentials, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.UserCredentials); ok {
		r0 = rf(ctx, username)
	} else {
		r0 = ret.Get(0).(domain.UserCredentials)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_GetUserCredentialsByUsername_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserCredentialsByUsername'
type StorageMock_GetUserCredentialsByUsername_Call struct {
	*mock.Call
}

// GetUserCredentialsByUsername is a helper method to define mock.On call
//   - ctx context.Context
//   - username string
func (_e *StorageMock_Expecter) GetUserCredentialsByUsername(ctx interface{}, username interface{}) *StorageMock_GetUserCredentialsByUsername_Call {
	return &StorageMock_GetUserCredentialsByUsername_Call{Call: _e.mock.On("GetUserCredentialsByUsername", ctx, username)}
}

func (_c *StorageMock_GetUserCredentialsByUsername_Call) Run(run func(ctx context.Context, username string)) *StorageMock_GetUserCredentialsByUsername_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *StorageMock_GetUserCredentialsByUsername_Call) Return(_a0 domain.UserCredentials, _a1 error) *StorageMock_GetUserCredentialsByUsername_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_GetUserCredentialsByUsername_Call) RunAndReturn(run func(context.Context, string) (domain.UserCredentials, error)) *StorageMock_GetUserCredentialsByUsername_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, currency, amountMinor
func (_m *StorageMock) Withdraw(ctx context.Context, userID int64, currency domain.Currency, amountMinor int64) (map[string]int64, error) {
	ret := _m.Called(ctx, userID, currency, amountMinor)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Currency, int64) (map[string]int64, error)); ok {
		return rf(ctx, userID, currency, amountMinor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, domain.Currency, int64) map[string]int64); ok {
		r0 = rf(ctx, userID, currency, amountMinor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, domain.Currency, int64) error); ok {
		r1 = rf(ctx, userID, currency, amountMinor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StorageMock_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type StorageMock_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - currency domain.Currency
//   - amountMinor int64
func (_e *StorageMock_Expecter) Withdraw(ctx interface{}, userID interface{}, currency interface{}, amountMinor interface{}) *StorageMock_Withdraw_Call {
	return &StorageMock_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, currency, amountMinor)}
}

func (_c *StorageMock_Withdraw_Call) Run(run func(ctx context.Context, userID int64, currency domain.Currency, amountMinor int64)) *StorageMock_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(domain.Currency), args[3].(int64))
	})
	return _c
}

func (_c *StorageMock_Withdraw_Call) Return(_a0 map[string]int64, _a1 error) *StorageMock_Withdraw_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StorageMock_Withdraw_Call) RunAndReturn(run func(context.Context, int64, domain.Currency, int64) (map[string]int64, error)) *StorageMock_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageMock creates a new instance of StorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageMock {
	mock := &StorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
