// Code generated by mockery. DO NOT EDIT.

package usecaseapimocks

import (
	context "context"

	domain "github.com/paxaf/itkFinal/gw-currency-wallet/internal/domain"
	usecase "github.com/paxaf/itkFinal/gw-currency-wallet/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// UseCaseMock is an autogenerated mock type for the UseCase type
type UseCaseMock struct {
	mock.Mock
}

type UseCaseMock_Expecter struct {
	mock *mock.Mock
}

func (_m *UseCaseMock) EXPECT() *UseCaseMock_Expecter {
	return &UseCaseMock_Expecter{mock: &_m.Mock}
}

// Deposit provides a mock function with given fields: ctx, userID, currency, amountMinor
func (_m *UseCaseMock) Deposit(ctx context.Context, userID int64, currency string, amountMinor int64) (map[string]int64, error) {
	ret := _m.Called(ctx, userID, currency, amountMinor)

	if len(ret) == 0 {
		panic("no return value specified for Deposit")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) (map[string]int64, error)); ok {
		return rf(ctx, userID, currency, amountMinor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) map[string]int64); ok {
		r0 = rf(ctx, userID, currency, amountMinor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = rf(ctx, userID, currency, amountMinor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseCaseMock_Deposit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Deposit'
type UseCaseMock_Deposit_Call struct {
	*mock.Call
}

// Deposit is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - currency string
//   - amountMinor int64
func (_e *UseCaseMock_Expecter) Deposit(ctx interface{}, userID interface{}, currency interface{}, amountMinor interface{}) *UseCaseMock_Deposit_Call {
	return &UseCaseMock_Deposit_Call{Call: _e.mock.On("Deposit", ctx, userID, currency, amountMinor)}
}

func (_c *UseCaseMock_Deposit_Call) Run(run func(ctx context.Context, userID int64, currency string, amountMinor int64)) *UseCaseMock_Deposit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *UseCaseMock_Deposit_Call) Return(_a0 map[string]int64, _a1 error) *UseCaseMock_Deposit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UseCaseMock_Deposit_Call) RunAndReturn(run func(context.Context, int64, string, int64) (map[string]int64, error)) *UseCaseMock_Deposit_Call {
	_c.Call.Return(run)
	return _c
}

// Exchange provides a mock function with given fields: ctx, op
func (_m *UseCaseMock) Exchange(ctx context.Context, op domain.ExchangeOperation) (usecase.ExchangeResult, error) {
	ret := _m.Called(ctx, op)

	if len(ret) == 0 {
		panic("no return value specified for Exchange")
	}

	var r0 usecase.ExchangeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ExchangeOperation) (usecase.ExchangeResult, error)); ok {
		return rf(ctx, op)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ExchangeOperation) usecase.ExchangeResult); ok {
		r0 = rf(ctx, op)
	} else {
		r0 = ret.Get(0).(usecase.ExchangeResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ExchangeOperation) error); ok {
		r1 = rf(ctx, op)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseCaseMock_Exchange_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exchange'
type UseCaseMock_Exchange_Call struct {
	*mock.Call
}

// Exchange is a helper method to define mock.On call
//   - ctx context.Context
//   - op domain.ExchangeOperation
func (_e *UseCaseMock_Expecter) Exchange(ctx interface{}, op interface{}) *UseCaseMock_Exchange_Call {
	return &UseCaseMock_Exchange_Call{Call: _e.mock.On("Exchange", ctx, op)}
}

func (_c *UseCaseMock_Exchange_Call) Run(run func(ctx context.Context, op domain.ExchangeOperation)) *UseCaseMock_Exchange_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.ExchangeOperation))
	})
	return _c
}

func (_c *UseCaseMock_Exchange_Call) Return(_a0 usecase.ExchangeResult, _a1 error) *UseCaseMock_Exchange_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UseCaseMock_Exchange_Call) RunAndReturn(run func(context.Context, domain.ExchangeOperation) (usecase.ExchangeResult, error)) *UseCaseMock_Exchange_Call {
	_c.Call.Return(run)
	return _c
}

// GetBalance provides a mock function with given fields: ctx, userID
func (_m *UseCaseMock) GetBalance(ctx context.Context, userID int64) (map[string]int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (map[string]int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) map[string]int64); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseCaseMock_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type UseCaseMock_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
func (_e *UseCaseMock_Expecter) GetBalance(ctx interface{}, userID interface{}) *UseCaseMock_GetBalance_Call {
	return &UseCaseMock_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *UseCaseMock_GetBalance_Call) Run(run func(ctx context.Context, userID int64)) *UseCaseMock_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UseCaseMock_GetBalance_Call) Return(_a0 map[string]int64, _a1 error) *UseCaseMock_GetBalance_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UseCaseMock_GetBalance_Call) RunAndReturn(run func(context.Context, int64) (map[string]int64, error)) *UseCaseMock_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// GetExchangeRates provides a mock function with given fields: ctx
func (_m *UseCaseMock) GetExchangeRates(ctx context.Context) (map[string]float64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetExchangeRates")
	}

	var r0 map[string]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]float64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]float64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseCaseMock_GetExchangeRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExchangeRates'
type UseCaseMock_GetExchangeRates_Call struct {
	*mock.Call
}

// GetExchangeRates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UseCaseMock_Expecter) GetExchangeRates(ctx interface{}) *UseCaseMock_GetExchangeRates_Call {
	return &UseCaseMock_GetExchangeRates_Call{Call: _e.mock.On("GetExchangeRates", ctx)}
}

func (_c *UseCaseMock_GetExchangeRates_Call) Run(run func(ctx context.Context)) *UseCaseMock_GetExchangeRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UseCaseMock_GetExchangeRates_Call) Return(_a0 map[string]float64, _a1 error) *UseCaseMock_GetExchangeRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UseCaseMock_GetExchangeRates_Call) RunAndReturn(run func(context.Context) (map[string]float64, error)) *UseCaseMock_GetExchangeRates_Call {
	_c.Call.Return(run)
	return _c
}

// Login provides a mock function with given fields: ctx, user
func (_m *UseCaseMock) Login(ctx context.Context, user domain.LoginUser) (string, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LoginUser) (string, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.LoginUser) string); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.LoginUser) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseCaseMock_Login_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Login'
type UseCaseMock_Login_Call struct {
	*mock.Call
}

// Login is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.LoginUser
func (_e *UseCaseMock_Expecter) Login(ctx interface{}, user interface{}) *UseCaseMock_Login_Call {
	return &UseCaseMock_Login_Call{Call: _e.mock.On("Login", ctx, user)}
}

func (_c *UseCaseMock_Login_Call) Run(run func(ctx context.Context, user domain.LoginUser)) *UseCaseMock_Login_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.LoginUser))
	})
	return _c
}

func (_c *UseCaseMock_Login_Call) Return(_a0 string, _a1 error) *UseCaseMock_Login_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UseCaseMock_Login_Call) RunAndReturn(run func(context.Context, domain.LoginUser) (string, error)) *UseCaseMock_Login_Call {
	_c.Call.Return(run)
	return _c
}

// Register provides a mock function with given fields: ctx, user
func (_m *UseCaseMock) Register(ctx context.Context, user domain.RegisterUser) (domain.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 domain.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.RegisterUser) (domain.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.RegisterUser) domain.User); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(domain.User)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.RegisterUser) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseCaseMock_Register_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Register'
type UseCaseMock_Register_Call struct {
	*mock.Call
}

// Register is a helper method to define mock.On call
//   - ctx context.Context
//   - user domain.RegisterUser
func (_e *UseCaseMock_Expecter) Register(ctx interface{}, user interface{}) *UseCaseMock_Register_Call {
	return &UseCaseMock_Register_Call{Call: _e.mock.On("Register", ctx, user)}
}

func (_c *UseCaseMock_Register_Call) Run(run func(ctx context.Context, user domain.RegisterUser)) *UseCaseMock_Register_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.RegisterUser))
	})
	return _c
}

func (_c *UseCaseMock_Register_Call) Return(_a0 domain.User, _a1 error) *UseCaseMock_Register_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UseCaseMock_Register_Call) RunAndReturn(run func(context.Context, domain.RegisterUser) (domain.User, error)) *UseCaseMock_Register_Call {
	_c.Call.Return(run)
	return _c
}

// Withdraw provides a mock function with given fields: ctx, userID, currency, amountMinor
func (_m *UseCaseMock) Withdraw(ctx context.Context, userID int64, currency string, amountMinor int64) (map[string]int64, error) {
	ret := _m.Called(ctx, userID, currency, amountMinor)

	if len(ret) == 0 {
		panic("no return value specified for Withdraw")
	}

	var r0 map[string]int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) (map[string]int64, error)); ok {
		return rf(ctx, userID, currency, amountMinor)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, string, int64) map[string]int64); ok {
		r0 = rf(ctx, userID, currency, amountMinor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, string, int64) error); ok {
		r1 = rf(ctx, userID, currency, amountMinor)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UseCaseMock_Withdraw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Withdraw'
type UseCaseMock_Withdraw_Call struct {
	*mock.Call
}

// Withdraw is a helper method to define mock.On call
//   - ctx context.Context
//   - userID int64
//   - currency string
//   - amountMinor int64
func (_e *UseCaseMock_Expecter) Withdraw(ctx interface{}, userID interface{}, currency interface{}, amountMinor interface{}) *UseCaseMock_Withdraw_Call {
	return &UseCaseMock_Withdraw_Call{Call: _e.mock.On("Withdraw", ctx, userID, currency, amountMinor)}
}

func (_c *UseCaseMock_Withdraw_Call) Run(run func(ctx context.Context, userID int64, currency string, amountMinor int64)) *UseCaseMock_Withdraw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(string), args[3].(int64))
	})
	return _c
}

func (_c *UseCaseMock_Withdraw_Call) Return(_a0 map[string]int64, _a1 error) *UseCaseMock_Withdraw_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UseCaseMock_Withdraw_Call) RunAndReturn(run func(context.Context, int64, string, int64) (map[string]int64, error)) *UseCaseMock_Withdraw_Call {
	_c.Call.Return(run)
	return _c
}

// NewUseCaseMock creates a new instance of UseCaseMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCaseMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCaseMock {
	mock := &UseCaseMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
