// Code generated by mockery. DO NOT EDIT.

package httpmocks

import mock "github.com/stretchr/testify/mock"

// TokenParserMock is an autogenerated mock type for the TokenParser type
type TokenParserMock struct {
	mock.Mock
}

type TokenParserMock_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenParserMock) EXPECT() *TokenParserMock_Expecter {
	return &TokenParserMock_Expecter{mock: &_m.Mock}
}

// Parse provides a mock function with given fields: tokenValue
func (_m *TokenParserMock) Parse(tokenValue string) (int64, error) {
	ret := _m.Called(tokenValue)

	if len(ret) == 0 {
		panic("no return value specified for Parse")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int64, error)); ok {
		return rf(tokenValue)
	}
	if rf, ok := ret.Get(0).(func(string) int64); ok {
		r0 = rf(tokenValue)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenValue)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenParserMock_Parse_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Parse'
type TokenParserMock_Parse_Call struct {
	*mock.Call
}

// Parse is a helper method to define mock.On call
//   - tokenValue string
func (_e *TokenParserMock_Expecter) Parse(tokenValue interface{}) *TokenParserMock_Parse_Call {
	return &TokenParserMock_Parse_Call{Call: _e.mock.On("Parse", tokenValue)}
}

func (_c *TokenParserMock_Parse_Call) Run(run func(tokenValue string)) *TokenParserMock_Parse_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenParserMock_Parse_Call) Return(_a0 int64, _a1 error) *TokenParserMock_Parse_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenParserMock_Parse_Call) RunAndReturn(run func(string) (int64, error)) *TokenParserMock_Parse_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenParserMock creates a new instance of TokenParserMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenParserMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenParserMock {
	mock := &TokenParserMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
