// Code generated by mockery. DO NOT EDIT.

package usecasemocks

import (
	context "context"

	events "github.com/paxaf/itkFinal/gw-currency-wallet/internal/clients/events"
	mock "github.com/stretchr/testify/mock"
)

// EventPublisherMock is an autogenerated mock type for the EventPublisher type
type EventPublisherMock struct {
	mock.Mock
}

type EventPublisherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *EventPublisherMock) EXPECT() *EventPublisherMock_Expecter {
	return &EventPublisherMock_Expecter{mock: &_m.Mock}
}

// PublishLargeOperation provides a mock function with given fields: ctx, event
func (_m *EventPublisherMock) PublishLargeOperation(ctx context.Context, event events.LargeOperationEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishLargeOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, events.LargeOperationEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventPublisherMock_PublishLargeOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishLargeOperation'
type EventPublisherMock_PublishLargeOperation_Call struct {
	*mock.Call
}

// PublishLargeOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - event events.LargeOperationEvent
func (_e *EventPublisherMock_Expecter) PublishLargeOperation(ctx interface{}, event interface{}) *EventPublisherMock_PublishLargeOperation_Call {
	return &EventPublisherMock_PublishLargeOperation_Call{Call: _e.mock.On("PublishLargeOperation", ctx, event)}
}

func (_c *EventPublisherMock_PublishLargeOperation_Call) Run(run func(ctx context.Context, event events.LargeOperationEvent)) *EventPublisherMock_PublishLargeOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(events.LargeOperationEvent))
	})
	return _c
}

func (_c *EventPublisherMock_PublishLargeOperation_Call) Return(_a0 error) *EventPublisherMock_PublishLargeOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventPublisherMock_PublishLargeOperation_Call) RunAndReturn(run func(context.Context, events.LargeOperationEvent) error) *EventPublisherMock_PublishLargeOperation_Call {
	_c.Call.Return(run)
	return _c
}

// PublishOperation provides a mock function with given fields: ctx, event
func (_m *EventPublisherMock) PublishOperation(ctx context.Context, event events.OperationEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, events.OperationEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EventPublisherMock_PublishOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishOperation'
type EventPublisherMock_PublishOperation_Call struct {
	*mock.Call
}

// PublishOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - event events.OperationEvent
func (_e *EventPublisherMock_Expecter) PublishOperation(ctx interface{}, event interface{}) *EventPublisherMock_PublishOperation_Call {
	return &EventPublisherMock_PublishOperation_Call{Call: _e.mock.On("PublishOperation", ctx, event)}
}

func (_c *EventPublisherMock_PublishOperation_Call) Run(run func(ctx context.Context, event events.OperationEvent)) *EventPublisherMock_PublishOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(events.OperationEvent))
	})
	return _c
}

func (_c *EventPublisherMock_PublishOperation_Call) Return(_a0 error) *EventPublisherMock_PublishOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *EventPublisherMock_PublishOperation_Call) RunAndReturn(run func(context.Context, events.OperationEvent) error) *EventPublisherMock_PublishOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewEventPublisherMock creates a new instance of EventPublisherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEventPublisherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *EventPublisherMock {
	mock := &EventPublisherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
