// Code generated by mockery. DO NOT EDIT.

package usecasemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ExchangeProviderMock is an autogenerated mock type for the ExchangeProvider type
type ExchangeProviderMock struct {
	mock.Mock
}

type ExchangeProviderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ExchangeProviderMock) EXPECT() *ExchangeProviderMock_Expecter {
	return &ExchangeProviderMock_Expecter{mock: &_m.Mock}
}

// GetRate provides a mock function with given fields: ctx, fromCurrency, toCurrency
func (_m *ExchangeProviderMock) GetRate(ctx context.Context, fromCurrency string, toCurrency string) (float64, error) {
	ret := _m.Called(ctx, fromCurrency, toCurrency)

	if len(ret) == 0 {
		panic("no return value specified for GetRate")
	}

	var r0 float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (float64, error)); ok {
		return rf(ctx, fromCurrency, toCurrency)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) float64); ok {
		r0 = rf(ctx, fromCurrency, toCurrency)
	} else {
		r0 = ret.Get(0).(float64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, fromCurrency, toCurrency)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExchangeProviderMock_GetRate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRate'
type ExchangeProviderMock_GetRate_Call struct {
	*mock.Call
}

// GetRate is a helper method to define mock.On call
//   - ctx context.Context
//   - fromCurrency string
//   - toCurrency string
func (_e *ExchangeProviderMock_Expecter) GetRate(ctx interface{}, fromCurrency interface{}, toCurrency interface{}) *ExchangeProviderMock_GetRate_Call {
	return &ExchangeProviderMock_GetRate_Call{Call: _e.mock.On("GetRate", ctx, fromCurrency, toCurrency)}
}

func (_c *ExchangeProviderMock_GetRate_Call) Run(run func(ctx context.Context, fromCurrency string, toCurrency string)) *ExchangeProviderMock_GetRate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *ExchangeProviderMock_GetRate_Call) Return(_a0 float64, _a1 error) *ExchangeProviderMock_GetRate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExchangeProviderMock_GetRate_Call) RunAndReturn(run func(context.Context, string, string) (float64, error)) *ExchangeProviderMock_GetRate_Call {
	_c.Call.Return(run)
	return _c
}

// GetRates provides a mock function with given fields: ctx
func (_m *ExchangeProviderMock) GetRates(ctx context.Context) (map[string]float64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRates")
	}

	var r0 map[string]float64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (map[string]float64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) map[string]float64); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]float64)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExchangeProviderMock_GetRates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRates'
type ExchangeProviderMock_GetRates_Call struct {
	*mock.Call
}

// GetRates is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ExchangeProviderMock_Expecter) GetRates(ctx interface{}) *ExchangeProviderMock_GetRates_Call {
	return &ExchangeProviderMock_GetRates_Call{Call: _e.mock.On("GetRates", ctx)}
}

func (_c *ExchangeProviderMock_GetRates_Call) Run(run func(ctx context.Context)) *ExchangeProviderMock_GetRates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ExchangeProviderMock_GetRates_Call) Return(_a0 map[string]float64, _a1 error) *ExchangeProviderMock_GetRates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ExchangeProviderMock_GetRates_Call) RunAndReturn(run func(context.Context) (map[string]float64, error)) *ExchangeProviderMock_GetRates_Call {
	_c.Call.Return(run)
	return _c
}

// NewExchangeProviderMock creates a new instance of ExchangeProviderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewExchangeProviderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ExchangeProviderMock {
	mock := &ExchangeProviderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
