// Code generated by mockery. DO NOT EDIT.

package usecasemocks

import (
	context "context"

	events "github.com/paxaf/itkFinal/gw-currency-wallet/internal/clients/events"
	mock "github.com/stretchr/testify/mock"
)

// LargeOperationPublisherMock is an autogenerated mock type for the LargeOperationPublisher type
type LargeOperationPublisherMock struct {
	mock.Mock
}

type LargeOperationPublisherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LargeOperationPublisherMock) EXPECT() *LargeOperationPublisherMock_Expecter {
	return &LargeOperationPublisherMock_Expecter{mock: &_m.Mock}
}

// PublishLargeOperation provides a mock function with given fields: ctx, event
func (_m *LargeOperationPublisherMock) PublishLargeOperation(ctx context.Context, event events.LargeOperationEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for PublishLargeOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, events.LargeOperationEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LargeOperationPublisherMock_PublishLargeOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishLargeOperation'
type LargeOperationPublisherMock_PublishLargeOperation_Call struct {
	*mock.Call
}

// PublishLargeOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - event events.LargeOperationEvent
func (_e *LargeOperationPublisherMock_Expecter) PublishLargeOperation(ctx interface{}, event interface{}) *LargeOperationPublisherMock_PublishLargeOperation_Call {
	return &LargeOperationPublisherMock_PublishLargeOperation_Call{Call: _e.mock.On("PublishLargeOperation", ctx, event)}
}

func (_c *LargeOperationPublisherMock_PublishLargeOperation_Call) Run(run func(ctx context.Context, event events.LargeOperationEvent)) *LargeOperationPublisherMock_PublishLargeOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(events.LargeOperationEvent))
	})
	return _c
}

func (_c *LargeOperationPublisherMock_PublishLargeOperation_Call) Return(_a0 error) *LargeOperationPublisherMock_PublishLargeOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LargeOperationPublisherMock_PublishLargeOperation_Call) RunAndReturn(run func(context.Context, events.LargeOperationEvent) error) *LargeOperationPublisherMock_PublishLargeOperation_Call {
	_c.Call.Return(run)
	return _c
}

// NewLargeOperationPublisherMock creates a new instance of LargeOperationPublisherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLargeOperationPublisherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LargeOperationPublisherMock {
	mock := &LargeOperationPublisherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
