// Code generated by mockery. DO NOT EDIT.

package loggermocks

import mock "github.com/stretchr/testify/mock"

// LoggerMock is an autogenerated mock type for the Interface type
type LoggerMock struct {
	mock.Mock
}

type LoggerMock_Expecter struct {
	mock *mock.Mock
}

func (_m *LoggerMock) EXPECT() *LoggerMock_Expecter {
	return &LoggerMock_Expecter{mock: &_m.Mock}
}

// Debug provides a mock function with given fields: message, args
func (_m *LoggerMock) Debug(message interface{}, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// LoggerMock_Debug_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Debug'
type LoggerMock_Debug_Call struct {
	*mock.Call
}

// Debug is a helper method to define mock.On call
//   - message interface{}
//   - args ...interface{}
func (_e *LoggerMock_Expecter) Debug(message interface{}, args ...interface{}) *LoggerMock_Debug_Call {
	return &LoggerMock_Debug_Call{Call: _e.mock.On("Debug",
		append([]interface{}{message}, args...)...)}
}

func (_c *LoggerMock_Debug_Call) Run(run func(message interface{}, args ...interface{})) *LoggerMock_Debug_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *LoggerMock_Debug_Call) Return() *LoggerMock_Debug_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerMock_Debug_Call) RunAndReturn(run func(interface{}, ...interface{})) *LoggerMock_Debug_Call {
	_c.Run(run)
	return _c
}

// Error provides a mock function with given fields: message, args
func (_m *LoggerMock) Error(message interface{}, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// LoggerMock_Error_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Error'
type LoggerMock_Error_Call struct {
	*mock.Call
}

// Error is a helper method to define mock.On call
//   - message interface{}
//   - args ...interface{}
func (_e *LoggerMock_Expecter) Error(message interface{}, args ...interface{}) *LoggerMock_Error_Call {
	return &LoggerMock_Error_Call{Call: _e.mock.On("Error",
		append([]interface{}{message}, args...)...)}
}

func (_c *LoggerMock_Error_Call) Run(run func(message interface{}, args ...interface{})) *LoggerMock_Error_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *LoggerMock_Error_Call) Return() *LoggerMock_Error_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerMock_Error_Call) RunAndReturn(run func(interface{}, ...interface{})) *LoggerMock_Error_Call {
	_c.Run(run)
	return _c
}

// Fatal provides a mock function with given fields: message, args
func (_m *LoggerMock) Fatal(message interface{}, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// LoggerMock_Fatal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Fatal'
type LoggerMock_Fatal_Call struct {
	*mock.Call
}

// Fatal is a helper method to define mock.On call
//   - message interface{}
//   - args ...interface{}
func (_e *LoggerMock_Expecter) Fatal(message interface{}, args ...interface{}) *LoggerMock_Fatal_Call {
	return &LoggerMock_Fatal_Call{Call: _e.mock.On("Fatal",
		append([]interface{}{message}, args...)...)}
}

func (_c *LoggerMock_Fatal_Call) Run(run func(message interface{}, args ...interface{})) *LoggerMock_Fatal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(interface{}), variadicArgs...)
	})
	return _c
}

func (_c *LoggerMock_Fatal_Call) Return() *LoggerMock_Fatal_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerMock_Fatal_Call) RunAndReturn(run func(interface{}, ...interface{})) *LoggerMock_Fatal_Call {
	_c.Run(run)
	return _c
}

// Info provides a mock function with given fields: message, args
func (_m *LoggerMock) Info(message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// LoggerMock_Info_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Info'
type LoggerMock_Info_Call struct {
	*mock.Call
}

// Info is a helper method to define mock.On call
//   - message string
//   - args ...interface{}
func (_e *LoggerMock_Expecter) Info(message interface{}, args ...interface{}) *LoggerMock_Info_Call {
	return &LoggerMock_Info_Call{Call: _e.mock.On("Info",
		append([]interface{}{message}, args...)...)}
}

func (_c *LoggerMock_Info_Call) Run(run func(message string, args ...interface{})) *LoggerMock_Info_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *LoggerMock_Info_Call) Return() *LoggerMock_Info_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerMock_Info_Call) RunAndReturn(run func(string, ...interface{})) *LoggerMock_Info_Call {
	_c.Run(run)
	return _c
}

// Warn provides a mock function with given fields: message, args
func (_m *LoggerMock) Warn(message string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, message)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}

// LoggerMock_Warn_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Warn'
type LoggerMock_Warn_Call struct {
	*mock.Call
}

// Warn is a helper method to define mock.On call
//   - message string
//   - args ...interface{}
func (_e *LoggerMock_Expecter) Warn(message interface{}, args ...interface{}) *LoggerMock_Warn_Call {
	return &LoggerMock_Warn_Call{Call: _e.mock.On("Warn",
		append([]interface{}{message}, args...)...)}
}

func (_c *LoggerMock_Warn_Call) Run(run func(message string, args ...interface{})) *LoggerMock_Warn_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]interface{}, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(interface{})
			}
		}
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *LoggerMock_Warn_Call) Return() *LoggerMock_Warn_Call {
	_c.Call.Return()
	return _c
}

func (_c *LoggerMock_Warn_Call) RunAndReturn(run func(string, ...interface{})) *LoggerMock_Warn_Call {
	_c.Run(run)
	return _c
}

// NewLoggerMock creates a new instance of LoggerMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLoggerMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *LoggerMock {
	mock := &LoggerMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
