// Code generated by mockery. DO NOT EDIT.

package kafkamocks

import (
	context "context"

	kafka_go "github.com/segmentio/kafka-go"
	mock "github.com/stretchr/testify/mock"
)

// ReaderMock is an autogenerated mock type for the Reader type
type ReaderMock struct {
	mock.Mock
}

type ReaderMock_Expecter struct {
	mock *mock.Mock
}

func (_m *ReaderMock) EXPECT() *ReaderMock_Expecter {
	return &ReaderMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with no fields
func (_m *ReaderMock) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReaderMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type ReaderMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *ReaderMock_Expecter) Close() *ReaderMock_Close_Call {
	return &ReaderMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *ReaderMock_Close_Call) Run(run func()) *ReaderMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ReaderMock_Close_Call) Return(_a0 error) *ReaderMock_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReaderMock_Close_Call) RunAndReturn(run func() error) *ReaderMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// CommitMessages provides a mock function with given fields: ctx, msgs
func (_m *ReaderMock) CommitMessages(ctx context.Context, msgs ...kafka_go.Message) error {
	_va := make([]interface{}, len(msgs))
	for _i := range msgs {
		_va[_i] = msgs[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CommitMessages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...kafka_go.Message) error); ok {
		r0 = rf(ctx, msgs...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ReaderMock_CommitMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitMessages'
type ReaderMock_CommitMessages_Call struct {
	*mock.Call
}

// CommitMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - msgs ...kafka_go.Message
func (_e *ReaderMock_Expecter) CommitMessages(ctx interface{}, msgs ...interface{}) *ReaderMock_CommitMessages_Call {
	return &ReaderMock_CommitMessages_Call{Call: _e.mock.On("CommitMessages",
		append([]interface{}{ctx}, msgs...)...)}
}

func (_c *ReaderMock_CommitMessages_Call) Run(run func(ctx context.Context, msgs ...kafka_go.Message)) *ReaderMock_CommitMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]kafka_go.Message, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(kafka_go.Message)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *ReaderMock_CommitMessages_Call) Return(_a0 error) *ReaderMock_CommitMessages_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *ReaderMock_CommitMessages_Call) RunAndReturn(run func(context.Context, ...kafka_go.Message) error) *ReaderMock_CommitMessages_Call {
	_c.Call.Return(run)
	return _c
}

// FetchMessage provides a mock function with given fields: ctx
func (_m *ReaderMock) FetchMessage(ctx context.Context) (kafka_go.Message, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchMessage")
	}

	var r0 kafka_go.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (kafka_go.Message, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) kafka_go.Message); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(kafka_go.Message)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReaderMock_FetchMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMessage'
type ReaderMock_FetchMessage_Call struct {
	*mock.Call
}

// FetchMessage is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ReaderMock_Expecter) FetchMessage(ctx interface{}) *ReaderMock_FetchMessage_Call {
	return &ReaderMock_FetchMessage_Call{Call: _e.mock.On("FetchMessage", ctx)}
}

func (_c *ReaderMock_FetchMessage_Call) Run(run func(ctx context.Context)) *ReaderMock_FetchMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *ReaderMock_FetchMessage_Call) Return(_a0 kafka_go.Message, _a1 error) *ReaderMock_FetchMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *ReaderMock_FetchMessage_Call) RunAndReturn(run func(context.Context) (kafka_go.Message, error)) *ReaderMock_FetchMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewReaderMock creates a new instance of ReaderMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReaderMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReaderMock {
	mock := &ReaderMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
