// Code generated by mockery. DO NOT EDIT.

package storagesmocks

import (
	context "context"

	domain "github.com/paxaf/itkFinal/gw-analytics/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// StorageMock is an autogenerated mock type for the Storage type
type StorageMock struct {
	mock.Mock
}

type StorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageMock) EXPECT() *StorageMock_Expecter {
	return &StorageMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *StorageMock) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type StorageMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StorageMock_Expecter) Close(ctx interface{}) *StorageMock_Close_Call {
	return &StorageMock_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *StorageMock_Close_Call) Run(run func(ctx context.Context)) *StorageMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StorageMock_Close_Call) Return(_a0 error) *StorageMock_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_Close_Call) RunAndReturn(run func(context.Context) error) *StorageMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOperation provides a mock function with given fields: ctx, event
func (_m *StorageMock) SaveOperation(ctx context.Context, event domain.OperationEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SaveOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.OperationEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageMock_SaveOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOperation'
type StorageMock_SaveOperation_Call struct {
	*mock.Call
}

// SaveOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.OperationEvent
func (_e *StorageMock_Expecter) SaveOperation(ctx interface{}, event interface{}) *StorageMock_SaveOperation_Call {
	return &StorageMock_SaveOperation_Call{Call: _e.mock.On("SaveOperation", ctx, event)}
}

func (_c *StorageMock_SaveOperation_Call) Run(run func(ctx context.Context, event domain.OperationEvent)) *StorageMock_SaveOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.OperationEvent))
	})
	return _c
}

func (_c *StorageMock_SaveOperation_Call) Return(_a0 error) *StorageMock_SaveOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_SaveOperation_Call) RunAndReturn(run func(context.Context, domain.OperationEvent) error) *StorageMock_SaveOperation_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOperations provides a mock function with given fields: ctx, events
func (_m *StorageMock) SaveOperations(ctx context.Context, events []domain.OperationEvent) error {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for SaveOperations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.OperationEvent) error); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageMock_SaveOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOperations'
type StorageMock_SaveOperations_Call struct {
	*mock.Call
}

// SaveOperations is a helper method to define mock.On call
//   - ctx context.Context
//   - events []domain.OperationEvent
func (_e *StorageMock_Expecter) SaveOperations(ctx interface{}, events interface{}) *StorageMock_SaveOperations_Call {
	return &StorageMock_SaveOperations_Call{Call: _e.mock.On("SaveOperations", ctx, events)}
}

func (_c *StorageMock_SaveOperations_Call) Run(run func(ctx context.Context, events []domain.OperationEvent)) *StorageMock_SaveOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.OperationEvent))
	})
	return _c
}

func (_c *StorageMock_SaveOperations_Call) Return(_a0 error) *StorageMock_SaveOperations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_SaveOperations_Call) RunAndReturn(run func(context.Context, []domain.OperationEvent) error) *StorageMock_SaveOperations_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageMock creates a new instance of StorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageMock {
	mock := &StorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
