// Code generated by mockery. DO NOT EDIT.

package storagesmocks

import (
	context "context"

	domain "github.com/paxaf/itkFinal/gw-notification/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// StorageMock is an autogenerated mock type for the Storage type
type StorageMock struct {
	mock.Mock
}

type StorageMock_Expecter struct {
	mock *mock.Mock
}

func (_m *StorageMock) EXPECT() *StorageMock_Expecter {
	return &StorageMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields: ctx
func (_m *StorageMock) Close(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type StorageMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StorageMock_Expecter) Close(ctx interface{}) *StorageMock_Close_Call {
	return &StorageMock_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *StorageMock_Close_Call) Run(run func(ctx context.Context)) *StorageMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *StorageMock_Close_Call) Return(_a0 error) *StorageMock_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_Close_Call) RunAndReturn(run func(context.Context) error) *StorageMock_Close_Call {
	_c.Call.Return(run)
	return _c
}

// SaveLargeOperation provides a mock function with given fields: ctx, event
func (_m *StorageMock) SaveLargeOperation(ctx context.Context, event domain.LargeOperationEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for SaveLargeOperation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.LargeOperationEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageMock_SaveLargeOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLargeOperation'
type StorageMock_SaveLargeOperation_Call struct {
	*mock.Call
}

// SaveLargeOperation is a helper method to define mock.On call
//   - ctx context.Context
//   - event domain.LargeOperationEvent
func (_e *StorageMock_Expecter) SaveLargeOperation(ctx interface{}, event interface{}) *StorageMock_SaveLargeOperation_Call {
	return &StorageMock_SaveLargeOperation_Call{Call: _e.mock.On("SaveLargeOperation", ctx, event)}
}

func (_c *StorageMock_SaveLargeOperation_Call) Run(run func(ctx context.Context, event domain.LargeOperationEvent)) *StorageMock_SaveLargeOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.LargeOperationEvent))
	})
	return _c
}

func (_c *StorageMock_SaveLargeOperation_Call) Return(_a0 error) *StorageMock_SaveLargeOperation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_SaveLargeOperation_Call) RunAndReturn(run func(context.Context, domain.LargeOperationEvent) error) *StorageMock_SaveLargeOperation_Call {
	_c.Call.Return(run)
	return _c
}

// SaveLargeOperations provides a mock function with given fields: ctx, events
func (_m *StorageMock) SaveLargeOperations(ctx context.Context, events []domain.LargeOperationEvent) error {
	ret := _m.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for SaveLargeOperations")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []domain.LargeOperationEvent) error); ok {
		r0 = rf(ctx, events)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StorageMock_SaveLargeOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLargeOperations'
type StorageMock_SaveLargeOperations_Call struct {
	*mock.Call
}

// SaveLargeOperations is a helper method to define mock.On call
//   - ctx context.Context
//   - events []domain.LargeOperationEvent
func (_e *StorageMock_Expecter) SaveLargeOperations(ctx interface{}, events interface{}) *StorageMock_SaveLargeOperations_Call {
	return &StorageMock_SaveLargeOperations_Call{Call: _e.mock.On("SaveLargeOperations", ctx, events)}
}

func (_c *StorageMock_SaveLargeOperations_Call) Run(run func(ctx context.Context, events []domain.LargeOperationEvent)) *StorageMock_SaveLargeOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]domain.LargeOperationEvent))
	})
	return _c
}

func (_c *StorageMock_SaveLargeOperations_Call) Return(_a0 error) *StorageMock_SaveLargeOperations_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *StorageMock_SaveLargeOperations_Call) RunAndReturn(run func(context.Context, []domain.LargeOperationEvent) error) *StorageMock_SaveLargeOperations_Call {
	_c.Call.Return(run)
	return _c
}

// NewStorageMock creates a new instance of StorageMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStorageMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *StorageMock {
	mock := &StorageMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
